### PR TITLE
#113 - Maven upload validation enabled

### LINKED ISSUE #113: Maven repository issues
There're some issues with Maven repository: it doesn't have any validation, `<versioning>` of metadata file may be incorrect if someone uploaded artifact just with `PUT` request, metadata file can be broken if user uploads valid `xml` metadata file with invalid artifact id and group id.

Consider changing maven deploy workflow to:
 1. Upload artifacts and checksum to temporary location, until `maven-metadata.xml` uploaded (always the last file of maven deploy)
 2. Perform some validation: check checksums are correct, check metadata group and id is the same as in repo `maven-metadata.xml` file, check metadata versions are correct.
 3. Merge new `maven-metadata.xml` file into current repo `maven-metadata.xml`, generate checksums for new metadata and rewrite it in temporary location
 4. Move all uploaded items and merged metadata file with updated checksums from temporary location to repository location

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #113, now all files are uploaded to the temp location, validated, metadata generated and copied to permanent location. Changes:
- `AstoMaven` generates `maven-metadata.xml` to temp location, uploaded version is read from uploaded `maven-metadata.xml`
- `ArtifactsMetadata` reads `release` version from `maven-metadata.xml` as uploaded `maven-metadata.xml` not necessarily contains `latest` tag, xml for the new artifact looks like this
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.apache.maven.resolver</groupId>
  <artifactId>maven-resolver-util</artifactId>
  <versioning>
    <release>1.3.3</release>
    <versions>
      <version>1.3.3</version>
    </versions>
    <lastUpdated>20200817054301</lastUpdated>
  </versioning>
</metadata>
``` 
- `AstoValidUpload` works properly with new artifact (when first version is uploaded)
- `AstoMavenITCase` corrected with usage `TestResource` from asto
- created #144 to handle snapshot properly

### CODE REVIEW

File: src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java [hunk 1]
```diff
@@ -57,15 +57,32 @@ public ArtifactsMetadata(final Storage storage) {
...
+                        if (xml.xpath(release).size() > 0) {
+                            res = xml.xpath(release).get(0);
+                        } else if (xml.xpath(latest).size() > 0) {
+                            res = xml.xpath(latest).get(0);
+                        } else {
+                            throw new IllegalArgumentException(
+                                "Maven metadata xml not valid: latest version not found"
+                            );
+                        }
+                        return res;
```
Comment (olegmoz) [inline src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java:83]: @olenagerasimova I think this logic deserves to be tested in different metadata XML files

File: src/test/java/com/artipie/maven/AstoMavenITCase.java [hunk 2]
```diff
@@ -66,155 +52,97 @@
...
-        meta.copy(asto.resolve(meta.name()));
+    void setUp() {
+        final Storage resources = new FileStorage(new TestResource("com/artipie/asto").asPath());
+        this.repository = new FileStorage(this.repo);
+        resources.list(Key.ROOT).thenCompose(
+            list -> CompletableFuture.allOf(list.stream()
+                .filter(
+                    item -> !item.string().contains("1.0-SNAPSHOT")
+                        && !item.string().contains("0.20.2")
+                        && !item.string().contains("maven-metadata.xml")
```
Comment (olegmoz) [inline src/test/java/com/artipie/maven/AstoMavenITCase.java:86]: @olenagerasimova version number and metadata file name constants are duplicated in the class and even in the method. I'd suggest to extract them to variables/fields

File: src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java (hunk 1 above)
Comment (olenagerasimova) [reply src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java:83]: @olegmoz it sure does, but I'm planing to extend this logic in #144 as xmls differ for snapshot/regular versions, I think proper test can be created along with this class next changes

**Comment by olenagerasimova** [comment]
@olegmoz thanks, corrected and answered, please, take a look

**Comment by olenagerasimova** [comment]
@g4s8 please check/merge

File: src/test/java/com/artipie/maven/AstoMavenITCase.java [hunk 3]
```diff
@@ -66,155 +52,99 @@
...
-            }
-        }
-        final TestResource meta = res.resolve("maven-metadata.xml");
-        meta.copy(asto.resolve(meta.name()));
+    void setUp() {
+        final Storage resources = new FileStorage(new TestResource("com/artipie/asto").asPath());
+        this.repository = new FileStorage(this.repo);
+        final String latest = "0.20.2";
+        final String meta = "maven-metadata.xml";
+        resources.list(Key.ROOT).thenCompose(
```
Comment (g4s8) [inline src/test/java/com/artipie/maven/AstoMavenITCase.java:83]: @olenagerasimova I'd use `BlockingStorage(storage)` for tests to simplify it

File: src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java [hunk 4]
```diff
@@ -57,15 +57,32 @@ public ArtifactsMetadata(final Storage storage) {
...
-                .thenApply(metadata -> new XMLDocument(metadata).xpath("//latest/text()").get(0))
+                .thenApply(
+                    metadata -> {
+                        final XMLDocument xml = new XMLDocument(metadata);
+                        final String latest = "//latest/text()";
+                        final String release = "//release/text()";
+                        final String res;
+                        if (xml.xpath(release).size() > 0) {
+                            res = xml.xpath(release).get(0);
+                        } else if (xml.xpath(latest).size() > 0) {
```
Comment (g4s8) [inline src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java:76]: @olenagerasimova `!isEmpty()` can be used here instead of `size() > 0`

**Comment by olenagerasimova** [comment]
@g4s8 thanks, please, take a look

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#145` is not assigned, can't get performer
